### ISSUE TITLE
spelling review 

### ISSUE THREAD

**Issue by davidljones** [joeflateau/ml_tree#6]
yeras to "years"
satistfaction  to "satisfaction"
we llok  to "we look"
upmost  to "utmost "

M L Tree Service is owned and operated by ISA Certified Arborist Michael Lynch. Michael has over ten years of experience working in the tree care industry. Through those years, Michael has been involved in all facets of tree work, from the largest removals to the most tedious trimming. With any work performed by M L Tree Service, quality, safety and our customer's satisfaction are always of the utmost importance. M L Tree Service is fully insured to protect our clients and their property. We look forward to providing you with professional, knowledgeable and top of the line service. Please contact us for a free estimate.

**Comment by joeflateau** [comment]
You resolved this with 827fc8220862fddc5c80c8b5e791ed1f93105b61
